//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechanicalAssistance.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MechanicalAssistance.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City was not found.
        /// </summary>
        public static string cityValidator {
            get {
                return ResourceManager.GetString("cityValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmation email has been sent. Confirm the account and log in to the application.
        /// </summary>
        public static string ConfirmEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Thank you for confirming your email. Now you can login into App..
        /// </summary>
        public static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string EmailLink {
            get {
                return ResourceManager.GetString("EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable the user, click on the following link:.
        /// </summary>
        public static string EmailMessage {
            get {
                return ResourceManager.GetString("EmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email was not found for some user.
        /// </summary>
        public static string EmailMessageValidation {
            get {
                return ResourceManager.GetString("EmailMessageValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail confirmation.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been changed correctly, check.
        /// </summary>
        public static string passMessage {
            get {
                return ResourceManager.GetString("passMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password entered is incorrect .
        /// </summary>
        public static string passValidation {
            get {
                return ResourceManager.GetString("passValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string RecoverLink {
            get {
                return ResourceManager.GetString("RecoverLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the following link to retrieve your password:.
        /// </summary>
        public static string RecoverMessage {
            get {
                return ResourceManager.GetString("RecoverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The steps to recover the password have been sent to the mail, please check..
        /// </summary>
        public static string RecoverSuccess {
            get {
                return ResourceManager.GetString("RecoverSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        public static string SubjectRecover {
            get {
                return ResourceManager.GetString("SubjectRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password Recovery.
        /// </summary>
        public static string titleRecover {
            get {
                return ResourceManager.GetString("titleRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip details have been saved correctly!.
        /// </summary>
        public static string tripDetailsMessage {
            get {
                return ResourceManager.GetString("tripDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trip has been saved correctly.
        /// </summary>
        public static string tripMessage {
            get {
                return ResourceManager.GetString("tripMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This trip does not exist!.
        /// </summary>
        public static string tripValidation {
            get {
                return ResourceManager.GetString("tripValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type Expenditure was not found.
        /// </summary>
        public static string typeExpenditureValidation {
            get {
                return ResourceManager.GetString("typeExpenditureValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Already Exists .
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Does Not Exits.
        /// </summary>
        public static string userValidator {
            get {
                return ResourceManager.GetString("userValidator", resourceCulture);
            }
        }

        public static string ServiceValidation
        {
            get
            {
                return ResourceManager.GetString("ServiceValidation", resourceCulture);
            }
        }

        public static string ProductBrandValidation
        {
            get
            {
                return ResourceManager.GetString("ProductBrandValidation", resourceCulture);
            }
        }

        public static string ProductMessage
        {
            get
            {
                return ResourceManager.GetString("ProductMessage", resourceCulture);
            }
        }

        
    }
}
